### ISSUE TITLE
Lists are not re-orderable

### ISSUE THREAD

**Issue by elkarouh** [rajasegar/htmx-trello#1]
In the readme, you say that this project was inspired by https://github.com/marconunnari/trello-clone
I am learning a lot from your code but there is a little difference with the above project.
The lists are not re-orderable (by dragging) in your project.
Can you give me a hint on how to implement such a feature?
Many thanks in advance

**Comment by rajasegar** [comment]
@elkarouh You can follow the same logic of the cards in a list for the lists in a board. You can make them draggable first and then add a sortable class to the board so that the sortable.js picks them up for processing.
See the changes here
https://github.com/rajasegar/htmx-trello/commit/0249e54f7e116ae0638b277a6ccee7f2758965b8
But we need to handle the events in the backend (routes) also

**Comment by elkarouh** [comment]
I made a quick test.
It seems to work.
Many thanks
